# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62e64b18365ebd839499d9f36f2fbb6985ca265a5ca0bfee1f68d16a6f8785ee088b64856b32959876298d5c40bdf4466ade0a06db7798167910dbdd0860b51f

test:
  secret_key_base: 2d4d7d4a8ce94966ec6d649375def53c1caac0d218cfa2a9e2140e652be234814fc7cc3ac772f52e02ed3063db15ad9167d3ffb5780bf88955e1d26c9e59930c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
